name: build

on: 
  push : 
    branch : [ source ]

jobs:
    
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependency
        run: npm install
      - run: npm run build
      - name: Deploy
        # uses: peaceiris/actions-gh-pages@v3
        # with:
        #   personal_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./public
        #   publish_branch: main
        uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }} # secret 名
          PUBLISH_REPOSITORY: zqc-cs/zqc-cs.github.io # 公共仓库，格式：GitHub 用户名/仓库名
          BRANCH: gh-pages # 分支，填 gh-pages 就行
          PUBLISH_DIR: ./public # 部署 public 目录下的文件